import React from 'react'
import styled from 'styled-components';
import useGlobalState from '../globalState/globalState';

export const ShowGlobalTexts = () => {
  const [globalError, setGlobalError] = useGlobalState('globalError');




  if(globalError !== '') {

      return (
          <Wrapper>
              <div className='error_box slide-in-right'>
                  <h4 className='error_text'> {globalError}</h4>
              </div>
             
              {/* clear error after 5 sec start */}
              <div className="setTimeout">
              {
                    setTimeout(() => {
                        setGlobalError('')
                    }, 9000)
              }
              </div>
             
              {/* clear error after 5 sec end */}

          </Wrapper>
      )
  }else {

    return (

        <Wrapper>
            
        </Wrapper>
    )
  }
}

const Wrapper = styled.div`
position: relative;

.error {
    &_box {
        padding: 1.1% 2.5% 1% 2.5%;
        background-color: var(--clr-red-light);
        border-radius: 0px 0 50px 50px;
        position: fixed;
        right: 0;
        z-index: 50000;
        
    }
    &_text {
        color: #fff;
        font-size: 1rem;
    }
}
.setTimeout {
    display: none;
}

.slide-in-right {
	-webkit-animation: slide-in-right 0.8s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
	        animation: slide-in-right 0.8s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
}

/* ----------------------------------------------
 * Generated by Animista on 2021-11-4 20:29:36
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation slide-in-right
 * ----------------------------------------
 */
 @-webkit-keyframes slide-in-right {
  0% {
    -webkit-transform: translateX(1000px);
            transform: translateX(1000px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateX(0);
            transform: translateX(0);
    opacity: 1;
  }
}
@keyframes slide-in-right {
  0% {
    -webkit-transform: translateX(1000px);
            transform: translateX(1000px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateX(0);
            transform: translateX(0);
    opacity: 1;
  }
}



`